# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 353a9be0ab450f3e61482c61175c5773b5fa7207e23b9dc53bc69402f939e0e03eb02b47336f76d60118802317ae7af65947d1cbb386350872999ebccd022199

test:
  secret_key_base: 9c3163442d9a75189298fa3c9098f4486cd758616e42d8e97df8be0eb77a4b480a392a587f86ace2776b572421562f15aac302ff5320e78d916a7dc1024cd18f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
